language: node_js

node_js:
  - 16
  
cache:
  directories:
    - node_modules

script:
- npm install
- npm run test:unit

after_script:
- npm run coverage

after_success:
- npm run build


deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 on:
   branch: main